spring:
  application:
    name: hotel-booking-service

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_booking_schema
      connection-timeout: 10000
  flyway:
    baseline-on-migrate: true
    baseline-version: 1

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.example.hotel_booking_service.kafka.dto.KafkaUserRegistrationEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  data:
    mongodb:
      authentication-database: admin
      database: hotel_booking_db
      port: 27017
      host: localhost