spring:
  application:
    name: hotel-booking-service

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_booking_db
    username: postgres
    password: postgres
    hikari:
      schema: hotel_booking_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS hotel_booking_schema
      connection-timeout: 10000
