CREATE TABLE hotel (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   title VARCHAR(255),
   city VARCHAR(255),
   distance INTEGER,
   rating INTEGER,
   numberofratings INTEGER,
   CONSTRAINT pk_hotel PRIMARY KEY (id)
);

CREATE TABLE room (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(255),
   room_number VARCHAR(255) NOT NULL,
   price DECIMAL NOT NULL,
   max_people INTEGER NOT NULL,
   hotel_id BIGINT NOT NULL,
   CONSTRAINT pk_room PRIMARY KEY (id)
);

CREATE TABLE room_unavailable_dates (
  room_id BIGINT NOT NULL,
   unavailable_date date
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   username VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL,
   CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE room ADD CONSTRAINT uc_room_room_number UNIQUE (room_number);

ALTER TABLE users ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE room ADD CONSTRAINT FK_ROOM_ON_HOTEL FOREIGN KEY (hotel_id) REFERENCES hotel (id);

ALTER TABLE room_unavailable_dates ADD CONSTRAINT fk_room_unavailable_dates_on_room FOREIGN KEY (room_id) REFERENCES room (id);